import Resume from '../components/Resume'
import Sidebar from '../components/Sidebar'
import { skills } from '../data/page-data'
import './globals.css'

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className='flex flex-col sm:flex-row'>
        <Sidebar />

        <main className='grow-full p-16 basis-2/3 bg-green ml-auto'>
          <Resume data = {skills} />
        {children}
        </main>
        </body>
    </html>
  )
}
